import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@/styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>motty93 web site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1 className={styles.title}>ようこそ！</h1>
        <h2 className={styles.content}>もてぃのサイトへ</h2>
      </header>

      <main className={styles.main}>
        <p className={styles.description}>まだなんも書いてないっす </p>
      </main>

      <footer className={styles.footer}>
        ©Copyright 2022
        <a href="https://twitter.com/smo_t93" target="_blank" rel="noopener noreferrer">
          もてぃ{' '}
        </a>
        All Rights Reserved.
      </footer>
    </div>
  )
}

export default Home
